server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
jwt:
  secret: your-super-secret-key
  expiration-ms: 3600000
aws:
  s3:
    bucket-name: secure-file-storage-s3-bucket
    region: eu-north-1
    aws-secret-name: /secure-file-storage/aws-credentials
    db-secret-name: /secure-storage-app/db-credentials

