server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  docker:
    compose:
      enabled: false
  flyway:
    baseline-on-migrate: true
    locations:
      - classpath:db/migration
    out-of-order: true
  security:
    user:
      name: myuser
      password: mypassword
jwt:
  secret: your-super-secret-key
  expiration-ms: 3600000
aws:
  s3:
    bucket-name: secure-file-storage-s3-bucket
    region: eu-north-1
    aws-secret-name: /secure-file-storage/aws-credentials
    db-secret-name: /secure-storage-app/db-credentials

logging:
  level:
    com.securefilestorage: DEBUG